[workspace]
members = [
    "pinnacle-api-defs",
    "api/rust",
    "api/rust/pinnacle-api-macros",
    "wlcs_pinnacle",
    "api/lua/build"
]
exclude = [
    "snowcap", # Submodule
    "lcat", # The docs building repo is currently cloned into this repo in CI
]

[workspace.package]
authors = ["Ottatop <ottatop1227@gmail.com>"]
edition = "2021"
repository = "https://github.com/pinnacle-comp/pinnacle/"

[workspace.dependencies]
# Tokio
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"]}
tokio-stream = { version = "0.1.15", features = ["net"] }
# gRPC
prost = "0.13.1"
tonic = "0.12.0"
tonic-reflection = "0.12.0"
tonic-build = "0.12.0"
# Tracing
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "registry"] }
# API definitions
pinnacle-api-defs = { path = "./pinnacle-api-defs" }
# Misc.
xkbcommon = "0.8.0"
xdg = "2.5.2"
bitflags = "2.5.0"
clap = { version = "4.5.7", features = ["derive"] }
dircpy = "0.3.16"
tempfile = "3.10.1"
indexmap = "2.2.6"

[workspace.dependencies.smithay]
git = "https://github.com/Smithay/smithay"
rev = "e7f0857"
# path = "../../git/smithay"
default-features = false
features = [
    "desktop",
    "wayland_frontend",
    # udev
    "backend_libinput",
    "backend_udev",
    "backend_drm",
    "backend_gbm",
    "backend_egl",
    "backend_session_libseat",
    "renderer_gl",
    "renderer_multi",
    # egl
    "use_system_lib",
    "backend_egl",
    # winit
    "backend_winit",
    "backend_drm",
    # xwayland
    "xwayland",
    "x11rb_event_source",
]

[workspace.lints.clippy]
too_many_arguments = "allow"
new_without_default = "allow"
type_complexity = "allow"
let_and_return = "allow"
dbg_macro = "warn"

########################################################################yo😎###########

[package]
name = "pinnacle"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0+"
description = "A WIP Smithay-based Wayland compositor, inspired by AwesomeWM"
readme = "README.md"
repository.workspace = true
keywords = ["wayland", "compositor", "smithay", "lua"]

[dependencies]
# Smithay
smithay = { workspace = true }
smithay-drm-extras = { git = "https://github.com/Smithay/smithay", rev = "e7f0857" }
# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = "0.2.3"
# Errors
anyhow = { version = "1.0.86", features = ["backtrace"] }
thiserror = "1.0.61"
# xcursor stuff
xcursor = { version = "0.3.5" }
image = { version = "0.25.1", default-features = false }
# gRPC
prost = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
# Tokio
tokio = { workspace = true, features = ["process", "io-util", "signal"] }
tokio-stream = { workspace = true }
# CLI
clap = { workspace = true }
cliclack = "0.3.1"
# Misc.
bitflags = { workspace = true }
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
shellexpand = { version = "3.1.0", features = ["path"] }
x11rb = { version = "0.13.1", default-features = false, features = ["composite"] }
xkbcommon = { workspace = true }
xdg = { workspace = true }
sysinfo = "0.31.2"
pinnacle-api-defs = { workspace = true }
dircpy = { workspace = true }
chrono = "0.4.38"
bytemuck = "1.16.1"
pinnacle-api = { path = "./api/rust", default-features = false }
gag = "1.0.0"
drm-sys = "0.7.0"
libdisplay-info-sys = { git = "https://github.com/Smithay/libdisplay-info-rs", rev = "a482d0d" }
indexmap = { workspace = true }
snowcap = { path = "./snowcap", optional = true }
snowcap-api = { path = "./snowcap/api/rust", optional = true }
assert_matches = "1.5.0"

[build-dependencies]
vergen-gitcl = { version = "1.0.0", features = ["rustc", "cargo", "si"] }

[dev-dependencies]
temp-env = "0.3.6"
tempfile = { workspace = true }
test-log = { version = "0.2.16", default-features = false, features = ["trace"] }
pinnacle = { path = ".", features = ["wlcs"], default-features = false }
pinnacle-api = { path = "./api/rust", default-features = false }

[features]
default = ["snowcap"]
snowcap = ["pinnacle-api/snowcap", "dep:snowcap", "dep:snowcap-api"]
testing = [
    "smithay/renderer_test",
]
wlcs = ["testing"]

[lints]
workspace = true
